version: "3"

volumes:
  sqldb_volume:

services:
  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - sqldb_volume:/var/opt/mssql
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Testing1122
      - MSSQL_PID=Developer
    